### ISSUE TITLE
Send list of reservations to slack

### ISSUE THREAD

**Issue by hirokiraj** [binarapps/slack-integrator#6]
Would be awesome to have slack command to list all reservations done for this day, can we do this?

**Comment by mbroderson** [comment]
Yeah, basically just add another bot and use reservations app to route. You can find details in Readme.

**Comment by hirokiraj** [comment]
As an alternative, we can use params for existing POST action.

How about situation like this, when slack command params is equal to 'list' we will send all registered so far reservations to the channel. This way we can use the same integration, and keep it simple (one outgoing and incoming webhook for one abstract module).

**Comment by mbroderson** [comment]
Yes, that's a good idea. Green light for this feature from me :+1:
